In [1]:
import numpy as np
import tensorflow as tf

# Define a 5x5 input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Reshape to match TensorFlow's expected input format: (batch_size, height, width, channels)
input_tensor = tf.constant(input_matrix.reshape(1, 5, 5, 1))

# Define a 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32).reshape(3, 3, 1, 1)

# Perform convolution with different stride and padding values
conv_valid_s1 = tf.nn.conv2d(input_tensor, kernel, strides=1, padding='VALID')
conv_same_s1 = tf.nn.conv2d(input_tensor, kernel, strides=1, padding='SAME')
conv_valid_s2 = tf.nn.conv2d(input_tensor, kernel, strides=2, padding='VALID')
conv_same_s2 = tf.nn.conv2d(input_tensor, kernel, strides=2, padding='SAME')

# Print output feature maps
print("Output with Stride=1, Padding='VALID':\n", conv_valid_s1.numpy().squeeze())
print("\nOutput with Stride=1, Padding='SAME':\n", conv_same_s1.numpy().squeeze())
print("\nOutput with Stride=2, Padding='VALID':\n", conv_valid_s2.numpy().squeeze())
print("\nOutput with Stride=2, Padding='SAME':\n", conv_same_s2.numpy().squeeze())


Output with Stride=1, Padding='VALID':
 [[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Output with Stride=1, Padding='SAME':
 [[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Output with Stride=2, Padding='VALID':
 [[-6. -6.]
 [-6. -6.]]

Output with Stride=2, Padding='SAME':
 [[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]
